### PR TITLE
Compatibility updates for Ember 2.12

### PR DESCRIPTION
**Pull request by tzellman**
This branch started as a base of your 2.9 compatibility branch.

The biggest item to note is that I had to skip 3 tests in `r-get-test.js` due to this issue: https://github.com/emberjs/ember.js/issues/15013

Other than that, the updates are related to dependency bumps, as well as the change to support `factoryFor`.

### CODE REVIEW

**Comment by taras** [comment]
This is awesome! Thank you so much!

I'm going to add you as a contributor to this repo so you can merge it when you think it's ready.

**Comment by tzellman** [comment]
Likewise! This addon is fantastic, and a staple for my apps.
I'll look into the CI failures first.

Since there were API changes (e.g. `r/mut` removal), I assume we should bump the version to 1.0.0 (or 0.5.0 if you would prefer).

**Comment by taras** [comment]
> This addon is fantastic, and a staple for my apps.

Very happy. Which helpers do you use?

> Since there were API changes (e.g. r/mut removal), I assume we should bump the version to 1.0.0 (or 0.5.0 if you would prefer).

Yeah. good idea.

**Comment by tzellman** [comment]
> Very happy. Which helpers do you use?

Primarily `r` in conjunction with `ember-composable-helpers`. `r/log` is also very useful.

> Yeah. good idea.

1.0.0 or 0.5.0 ?

**Comment by taras** [comment]
Let's go for 0.5.0. Can you please remove `keep-latest` helper because I don't think it's necessary with `ember-concurrency` in the picture.

**Comment by tzellman** [comment]
Sure thing.

**Pull request merged**
